# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7918bae16226c1e3be8228bf95d2ac56f6ff18d3c30683ffbb1126f881bfda0db3e2e38444d7bc203617478a81b6c8ca6a50af1f87c2c1e0b18c4c2a364d307b

test:
  secret_key_base: 27cea4a5395cfd384759aa67a4661d49b787cf8d7d4975a22e7d170f1df140cd3b9935669c749b616db4acfd13d5dfa54699905e54091c20db9e37a498bf7772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
